#!/usr/bin/env python3
"""
action.py — I/O layer for the deep-research Skill.

Pure deterministic code. Reads M3's JSON output (topic + 4 sections + 3+
grounded notes) and renders the research markdown to
`04 Resources/research-YYYY-MM-DD-<topic-slug>.md`.

Esalen split: M3 does the qualitative judgment (what Andre believes,
what contradicts, what's missing, the unasked question). Python does the
deterministic I/O (filename, render, write, audit log).

Usage (programmatic):
    import action
    result = action.render_research(m3_output, date="2026-06-02")

Usage (CLI):
    action.py --m3-output /tmp/m3-research.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

__version__ = "0.1.0"

# ============================================================
# PATHS
# ============================================================

VAULT_ROOT = Path("/Users/brassfieldventuresllc/MiniMax-Agent")
RESOURCES_DIR = VAULT_ROOT / "04 Resources"
AUDIT_LOG = VAULT_ROOT / "99 _system" / "logs" / "deep-research-audit.jsonl"

MIN_GROUNDED_NOTES = 3
MIN_SECTION_PARAGRAPHS = 2  # each section needs 2+ paragraphs


# ============================================================
# VALIDATION
# ============================================================

def _count_paragraphs(text: str) -> int:
    """Count non-empty paragraphs (separated by blank lines)."""
    if not text:
        return 0
    return len([p for p in re.split(r"\n\s*\n", text.strip()) if p.strip()])


def validate_m3_output(m3_output: dict) -> None:
    """Raise ValueError on bad M3 output."""
    if not isinstance(m3_output, dict):
        raise ValueError(f"m3_output must be a dict, got: {type(m3_output).__name__}")

    for field in ("topic", "research_date", "what_andre_believes",
                  "what_contradicts", "what_is_missing", "unasked_question",
                  "grounded_notes"):
        if field not in m3_output:
            raise ValueError(f"missing required field: {field!r}")

    if not str(m3_output["topic"]).strip():
        raise ValueError("topic must be a non-empty string")
    try:
        datetime.strptime(m3_output["research_date"], "%Y-%m-%d")
    except ValueError:
        raise ValueError(f"research_date must be YYYY-MM-DD, got: {m3_output['research_date']!r}")

    # Each section needs 2+ paragraphs
    for section in ("what_andre_believes", "what_contradicts", "what_is_missing"):
        n = _count_paragraphs(m3_output[section])
        if n < MIN_SECTION_PARAGRAPHS:
            raise ValueError(
                f"{section} needs {MIN_SECTION_PARAGRAPHS}+ paragraphs, got {n}"
            )

    if not str(m3_output["unasked_question"]).strip():
        raise ValueError("unasked_question is required and must be non-empty")

    if not isinstance(m3_output["grounded_notes"], list):
        raise ValueError("grounded_notes must be a list")
    if len(m3_output["grounded_notes"]) < MIN_GROUNDED_NOTES:
        raise ValueError(
            f"grounded_notes needs {MIN_GROUNDED_NOTES}+ items, got {len(m3_output['grounded_notes'])}"
        )


# ============================================================
# MARKDOWN RENDER
# ============================================================

def slugify_topic(topic: str) -> str:
    """Convert a topic string to a kebab-case slug (max 60 chars)."""
    slug = re.sub(r"[^a-z0-9]+", "-", topic.lower()).strip("-")[:60]
    return slug or "untitled"


def render_research_markdown(m3_output: dict) -> str:
    """Render M3's JSON to the research markdown per the format in skill.md."""
    date = m3_output["research_date"]
    topic = m3_output["topic"]
    grounded_str = ", ".join(m3_output["grounded_notes"])

    lines = [
        f"# Deep Research: {topic}",
        "",
        f"_Generated by deep-research Skill Pack v{__version__} on {date}_",
        "",
        f"**Topic**: {topic}",
        f"**Date**: {date}",
        f"**Grounded in**: {grounded_str}",
        "",
        "---",
        "",
        "## 1. What Andre already believes",
        "",
        m3_output["what_andre_believes"].strip(),
        "",
        "## 2. What contradicts that belief",
        "",
        m3_output["what_contradicts"].strip(),
        "",
        "## 3. What perspective is clearly missing",
        "",
        m3_output["what_is_missing"].strip(),
        "",
        "## 4. The single most important unasked question",
        "",
        f"> {m3_output['unasked_question'].strip()}",
        "",
        "---",
        "",
        "## Notes",
        "",
        f"This research file is the output of the deep-research Skill Pack. The unasked question (section 4) is the load-bearing output — if you can only do one thing with this file, sit with that question for a week.",
    ]
    return "\n".join(lines) + "\n"


# ============================================================
# AUDIT LOG
# ============================================================

def write_audit_log(entry: dict) -> None:
    AUDIT_LOG.parent.mkdir(parents=True, exist_ok=True)
    with AUDIT_LOG.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")


# ============================================================
# MAIN ENTRYPOINT
# ============================================================

def render_research(
    m3_output: dict,
    *,
    date: str | None = None,
    overwrite: bool = False,
) -> dict:
    """Validate M3's JSON, render the research markdown, write the file."""
    validate_m3_output(m3_output)

    research_date = date or m3_output["research_date"]
    if date and date != m3_output["research_date"]:
        m3_output = {**m3_output, "research_date": date}

    topic_slug = slugify_topic(m3_output["topic"])
    out_path = RESOURCES_DIR / f"research-{research_date}-{topic_slug}.md"
    if out_path.exists() and not overwrite:
        raise FileExistsError(
            f"research file already exists: {out_path} (use overwrite=True)"
        )

    markdown = render_research_markdown(m3_output)
    out_path.write_text(markdown, encoding="utf-8")

    audit_entry = {
        "ts": datetime.now().isoformat(timespec="seconds"),
        "topic": m3_output["topic"],
        "topic_slug": topic_slug,
        "research_date": research_date,
        "path": str(out_path.relative_to(VAULT_ROOT)),
        "grounded_notes_count": len(m3_output["grounded_notes"]),
        "unasked_question": m3_output["unasked_question"][:200],
        "overwrite": overwrite,
        "script_version": __version__,
    }
    write_audit_log(audit_entry)

    return {
        "path": str(out_path.relative_to(VAULT_ROOT)),
        "topic": m3_output["topic"],
        "research_date": research_date,
        "grounded_notes_count": len(m3_output["grounded_notes"]),
        "audit_logged": True,
        "status": "ok",
    }


# ============================================================
# CLI
# ============================================================

def main() -> int:
    ap = argparse.ArgumentParser(
        prog="action.py",
        description="I/O layer for the deep-research Skill. Reads M3 JSON "
                    "from --m3-output and writes the research file to 04 Resources/.",
    )
    ap.add_argument("--m3-output", help="Path to a file containing M3's JSON output")
    ap.add_argument("--date", help="Override research date (YYYY-MM-DD)")
    ap.add_argument("--overwrite", action="store_true", help="Overwrite existing research file")
    ap.add_argument("--version", action="version", version=f"action.py v{__version__}")
    args = ap.parse_args()

    if not args.m3_output:
        ap.error("--m3-output is required (omit for --version)")

    try:
        m3_output = json.loads(Path(args.m3_output).read_text(encoding="utf-8"))
        result = render_research(m3_output, date=args.date, overwrite=args.overwrite)
        print(json.dumps(result, indent=2))
        return 0
    except Exception as e:
        print(f"action.py: {type(e).__name__}: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
