#!/usr/bin/env python3
"""
action.py — I/O layer for the daily-brief Skill.

Pure deterministic code. Reads M3's JSON output (3 connections, 1 pattern,
1 question) and renders the markdown brief to `00 Inbox/brief-YYYY-MM-DD.md`.
NO LLM calls here — all content decisions come from M3's JSON per the schema
in skill.md.

Esalen split: M3 does the qualitative judgment (which notes connect, what
the pattern is, what question matters). Python does the deterministic I/O
(render markdown, write file, append to today's daily, audit log). Tests
cover Python; M3-as-judge evals cover M3.

Usage (programmatic):
    import action
    result = action.render_brief(m3_output, date="2026-06-02", overwrite=False)

Usage (CLI):
    action.py --m3-output /tmp/m3-brief.json --date 2026-06-02
    action.py --m3-output /tmp/m3-brief.json --overwrite
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

__version__ = "0.1.0"

# ============================================================
# PATHS — vault-resident, hardcoded for the MiniMax-Agent vault
# ============================================================

VAULT_ROOT = Path("/Users/brassfieldventuresllc/MiniMax-Agent")
INBOX = VAULT_ROOT / "00 Inbox"
DAILY = VAULT_ROOT / "01 Daily"
AUDIT_LOG = VAULT_ROOT / "99 _system" / "logs" / "daily-brief-audit.jsonl"

# Minimum character length for source quotes (per skill.md rule)
MIN_QUOTE_CHARS = 15


# ============================================================
# VALIDATION
# ============================================================

def validate_m3_output(m3_output: dict) -> None:
    """Raise ValueError on missing/invalid M3 output. The deterministic
    layer that refuses to silently write a malformed brief."""
    if not isinstance(m3_output, dict):
        raise ValueError(f"m3_output must be a dict, got: {type(m3_output).__name__}")

    # brief_date
    if "brief_date" not in m3_output:
        raise ValueError("missing required field: brief_date")
    try:
        datetime.strptime(m3_output["brief_date"], "%Y-%m-%d")
    except ValueError:
        raise ValueError(f"brief_date must be YYYY-MM-DD, got: {m3_output['brief_date']!r}")

    # connections: must be a list of 0-3 items
    if "connections" not in m3_output or not isinstance(m3_output["connections"], list):
        raise ValueError("connections must be a list")
    if len(m3_output["connections"]) > 3:
        raise ValueError(f"too many connections ({len(m3_output['connections'])}); max 3")
    for i, c in enumerate(m3_output["connections"]):
        for field in ("headline", "source_note_1", "source_quote_1", "source_note_2", "source_quote_2"):
            if field not in c:
                raise ValueError(f"connections[{i}] missing field: {field!r}")
        for q in (c["source_quote_1"], c["source_quote_2"]):
            if len(q) < MIN_QUOTE_CHARS:
                raise ValueError(
                    f"connections[{i}] source quote too short ({len(q)} chars < {MIN_QUOTE_CHARS}): {q!r}"
                )

    # pattern: exactly 1
    if "pattern" not in m3_output or not isinstance(m3_output["pattern"], dict):
        raise ValueError("pattern must be a dict")
    for field in ("name", "evidence_notes"):
        if field not in m3_output["pattern"]:
            raise ValueError(f"pattern missing field: {field!r}")
    if not isinstance(m3_output["pattern"]["evidence_notes"], list):
        raise ValueError("pattern.evidence_notes must be a list")
    if len(m3_output["pattern"]["evidence_notes"]) < 3:
        raise ValueError(
            f"pattern.evidence_notes needs 3+ items, got {len(m3_output['pattern']['evidence_notes'])}"
        )

    # question
    if "question" not in m3_output or not str(m3_output["question"]).strip():
        raise ValueError("question is required and must be non-empty")


# ============================================================
# MARKDOWN RENDER
# ============================================================

def render_brief_markdown(m3_output: dict) -> str:
    """Render M3's JSON to the brief markdown per the format in skill.md."""
    lines = []
    date = m3_output["brief_date"]

    lines.append(f"# Daily Brief — {date}")
    lines.append("")
    lines.append(f"_Generated by daily-brief Skill Pack v{__version__}_")
    lines.append("")

    # CONNECTIONS
    lines.append("## CONNECTIONS — 3 specific connections")
    lines.append("")
    connections = m3_output["connections"]
    if not connections:
        lines.append("_Nothing to surface this morning — the inbox and recent notes are empty._")
        lines.append("")
    else:
        for i, c in enumerate(connections, 1):
            lines.append(f"### {i}. {c['headline']}")
            lines.append("")
            lines.append(f"- **{c['source_note_1']}**")
            lines.append(f"  > {c['source_quote_1']}")
            lines.append(f"- **{c['source_note_2']}**")
            lines.append(f"  > {c['source_quote_2']}")
            lines.append("")

    # PATTERN
    lines.append("## PATTERN — 1 pattern across the week")
    lines.append("")
    pattern = m3_output["pattern"]
    if "nothing to surface" in pattern.get("name", "").lower():
        lines.append(f"_{pattern['name']}_")
    else:
        lines.append(f"**{pattern['name']}**")
        lines.append("")
        lines.append("Evidence:")
        for note in pattern["evidence_notes"]:
            lines.append(f"- {note}")
    lines.append("")

    # QUESTION
    lines.append("## QUESTION — 1 question worth sitting with")
    lines.append("")
    question = m3_output["question"]
    if "nothing to surface" in question.lower():
        lines.append(f"_{question}_")
    else:
        lines.append(f"> {question}")
    lines.append("")

    return "\n".join(lines)


# ============================================================
# AUDIT LOG
# ============================================================

def write_audit_log(entry: dict) -> None:
    """Append a single JSONL entry to the daily-brief audit log."""
    AUDIT_LOG.parent.mkdir(parents=True, exist_ok=True)
    with AUDIT_LOG.open("a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")


# ============================================================
# MAIN ENTRYPOINT
# ============================================================

def render_brief(
    m3_output: dict,
    *,
    date: str | None = None,
    overwrite: bool = False,
) -> dict:
    """Validate M3's JSON, render the brief markdown, write the file.

    Args:
        m3_output: the JSON object M3 produced per skill.md schema
        date: optional ISO date override (defaults to m3_output["brief_date"])
        overwrite: if True, overwrite an existing brief for the same date

    Returns:
        dict with: brief_path, date, connections_count, audit_logged, status

    Raises:
        ValueError: bad m3_output
        FileExistsError: brief for that date already exists (when overwrite=False)
    """
    validate_m3_output(m3_output)

    brief_date = date or m3_output["brief_date"]
    # Sanity: --date and m3_output["brief_date"] should match
    if date and date != m3_output["brief_date"]:
        # Tolerate but record
        m3_output = {**m3_output, "brief_date": date}

    out_path = INBOX / f"brief-{brief_date}.md"
    if out_path.exists() and not overwrite:
        raise FileExistsError(
            f"brief already exists for {brief_date}: {out_path} (use overwrite=True)"
        )

    markdown = render_brief_markdown(m3_output)
    out_path.write_text(markdown, encoding="utf-8")

    # Optional: append a one-liner to today's daily note
    daily_path = DAILY / f"{brief_date}.md"
    daily_appended = False
    if daily_path.exists():
        with daily_path.open("a", encoding="utf-8") as f:
            f.write(f"\n\n> Daily brief generated: see `[[{out_path.name}]]`\n")
        daily_appended = True

    # Audit log
    audit_entry = {
        "ts": datetime.now().isoformat(timespec="seconds"),
        "brief_date": brief_date,
        "path": str(out_path.relative_to(VAULT_ROOT)),
        "connections_count": len(m3_output.get("connections", [])),
        "pattern_name": m3_output.get("pattern", {}).get("name", "")[:100],
        "question": m3_output.get("question", "")[:200],
        "daily_appended": daily_appended,
        "overwrite": overwrite,
        "script_version": __version__,
    }
    write_audit_log(audit_entry)

    return {
        "brief_path": str(out_path.relative_to(VAULT_ROOT)),
        "date": brief_date,
        "connections_count": len(m3_output.get("connections", [])),
        "audit_logged": True,
        "daily_appended": daily_appended,
        "status": "ok",
    }


# ============================================================
# CLI
# ============================================================

def main() -> int:
    ap = argparse.ArgumentParser(
        prog="action.py",
        description="I/O layer for the daily-brief Skill. Reads M3 JSON from "
                    "--m3-output, renders the brief, writes to 00 Inbox/.",
    )
    ap.add_argument("--m3-output", help="Path to a file containing M3's JSON output")
    ap.add_argument("--date", help="Override brief date (YYYY-MM-DD)")
    ap.add_argument("--overwrite", action="store_true", help="Overwrite existing brief for the date")
    ap.add_argument("--version", action="version", version=f"action.py v{__version__}")
    args = ap.parse_args()

    if not args.m3_output:
        ap.error("--m3-output is required (omit for --version)")

    try:
        m3_output = json.loads(Path(args.m3_output).read_text(encoding="utf-8"))
        result = render_brief(m3_output, date=args.date, overwrite=args.overwrite)
        print(json.dumps(result, indent=2))
        return 0
    except Exception as e:
        print(f"action.py: {type(e).__name__}: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
